In [1]:
import numpy as np

#### List Comprehension Example

In [2]:
S = [x**2 for x in range(10)]
S

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [3]:
M = [x for x in S if x%2 == 0]
M

[0, 4, 16, 36, 64]

In [4]:
V = [2**x for x in range(13)]
V

[1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096]

In [5]:
[x**3 for x in range(11)]

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [6]:
matrix = [[j for j in range(4)] for i in range(8)]
matrix

[[0, 1, 2, 3],
 [0, 1, 2, 3],
 [0, 1, 2, 3],
 [0, 1, 2, 3],
 [0, 1, 2, 3],
 [0, 1, 2, 3],
 [0, 1, 2, 3],
 [0, 1, 2, 3]]

In [7]:
matrix = [[1, 2, 3], [4, 5], [6, 7, 8, 9]] 
  
flatten_matrix = [val for sublist in matrix for val in sublist] 
  
flatten_matrix

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
planets = [['Mercury', 'Venus', 'Earth'], ['Mars', 'Jupiter', 'Saturn'], ['Uranus', 'Neptune', 'Pluto']]
[planet if len(planet) < 6 else '0' for sublist in planets for planet in sublist]

['0', 'Venus', 'Earth', 'Mars', '0', '0', '0', '0', 'Pluto']

In [9]:
planets = [['Mercury', 'Venus', 'Earth'], ['Mars', 'Jupiter', 'Saturn'], ['Uranus', 'Neptune', 'Pluto']]
[planet for sublist in planets for planet in sublist if len(planet) < 6]

['Venus', 'Earth', 'Mars', 'Pluto']

In [10]:
Input = ['Geeeks, Forgeeks', '65.7492, 62.5405', 
         'Geeks, 123', '555.7492, 152.5406'] 
[pair.split(', ') for pair in Input]

[['Geeeks', 'Forgeeks'],
 ['65.7492', '62.5405'],
 ['Geeks', '123'],
 ['555.7492', '152.5406']]

In [11]:
'a b c'.split(' ')

['a', 'b', 'c']

## 1109. Booking Problem Self-written Solution (did not pass the runtime limit)

In [12]:
bookings = [[1,2,10],[2,3,20],[2,5,25]]
n = 5

def corpFlightBookings(bookings, n):
    
        return [sum( bk[2] for bk in bookings if (i >= bk[0] and i <= bk[1]) ) for i in range(1,n+1)]

In [13]:
corpFlightBookings(bookings, n)

[10, 55, 45, 25, 25]

In [14]:
def corpFlightBookings_2(bookings, n):
    output = [0] * n
    for booking in bookings:
        for i in range(booking[0]-1, booking[1]):
            output[i] += booking[2]
    return output

In [15]:
corpFlightBookings_2(bookings, n)

[10, 55, 45, 25, 25]

#### Elegant and epic method!

#### res means result in programming

In [16]:
def corpFlightBookings_copied(bookings, n):  
    res = [0]*n

    for i in range(len(bookings)):   
        res[bookings[i][0]-1] += bookings[i][2]
        if bookings[i][1] < n:
            res[bookings[i][1]] -= bookings[i][2]

    s = 0
    for i in range(len(res)):
        res[i]+= s
        s = res[i]

    return res

In [17]:
corpFlightBookings_copied(bookings, n)

[10, 55, 45, 25, 25]

#### dictionary comprehenshion

In [18]:
l1 = ["eat","sleep","repeat"] 
s1 = "geek"
  
# creating enumerate objects 
obj1 = enumerate(l1) 
obj2 = enumerate(s1) 
  
print ("Return type:",type(obj1))
print (list(enumerate(l1)))
  
# changing start index to 2 from 0 
print (list(enumerate(s1,2)))

Return type: <class 'enumerate'>
[(0, 'eat'), (1, 'sleep'), (2, 'repeat')]
[(2, 'g'), (3, 'e'), (4, 'e'), (5, 'k')]


In [19]:
lst = ['A','B','C']
{k: v for v, k in enumerate(lst)}

{'A': 0, 'B': 1, 'C': 2}

#### Multiple elif condition by nested inside else

In [20]:
L = [0 if x%4 == 0 else 1 if x%4 == 1 else 2 if x%4 == 2 else 3 for x in range(20)]
L

[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]

#### Numpy Operation

In [21]:
from statistics import median 
x = np.array([[1, 2, 3, 4], [5, 6, 7 ,8], [9, 10, 11, 12]])

xm = np.vstack(([x[i,:] - median(x[i,:]) for i in range(x.shape[0])]))
xm

array([[-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5]])

In [22]:
x - np.median(x, axis=1)[:, np.newaxis]

array([[-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5]])

In [23]:
x - np.median(x, axis=1)[:, None]

array([[-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5]])

In [24]:
x - np.median(x, axis=1, keepdims=True)

array([[-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5]])

In [25]:
x - np.apply_along_axis(median, 1, x)[:,np.newaxis]

array([[-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5]])

In [26]:
x - np.apply_along_axis(median, 1, x)[:, None]

array([[-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5]])

In [27]:
{1:'a', 2:'b', 3:'c'}

{1: 'a', 2: 'b', 3: 'c'}

In [28]:
def my_func(a):
    """Average first and last element of a 1-D array"""
    return (a[0] + a[-1]) * 0.5
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.apply_along_axis(my_func, 0, b)

array([4., 5., 6.])

In [29]:
np.apply_along_axis(my_func, 1, b)

array([2., 5., 8.])

In [30]:
b = np.array([[8,1,7], [4,3,9], [5,2,6]])
np.apply_along_axis(sorted, 1, b)

array([[1, 7, 8],
       [3, 4, 9],
       [2, 5, 6]])

For a function that returns a higher dimensional array, those dimensions are inserted in place of the axis dimension.

In [31]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.apply_along_axis(np.diag, -1, b)

array([[[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]],

       [[4, 0, 0],
        [0, 5, 0],
        [0, 0, 6]],

       [[7, 0, 0],
        [0, 8, 0],
        [0, 0, 9]]])

In [32]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [33]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])

In [34]:
[x[i,:] - median(x[i,:]) for i in range(x.shape[0])]

[array([-1.5, -0.5,  0.5,  1.5]),
 array([-1.5, -0.5,  0.5,  1.5]),
 array([-1.5, -0.5,  0.5,  1.5])]

In [35]:
np.vstack([np.array([1,2,3]),np.array([4,5,6]), np.array([7,8,9])])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Get unique value by zip: parallel iteration

In [36]:
a = np.array([0, 3, 0, 1, 0, 1, 2, 1, 0, 0, 0, 0, 1, 3, 4])
unique, counts = np.unique(a, return_counts=True)
dict(zip(unique, counts))

{0: 7, 1: 4, 2: 1, 3: 2, 4: 1}

In [37]:
np.unique(a, return_counts=True)

(array([0, 1, 2, 3, 4]), array([7, 4, 1, 2, 1]))

In [41]:
np.unique(a)

array([0, 1, 2, 3, 4])

In [42]:
list(zip(np.array([1,2,3]), np.array([4,5,6])))

[(1, 4), (2, 5), (3, 6)]

In [43]:
tuple(zip(np.array([1,2,3]), np.array([4,5,6])))

((1, 4), (2, 5), (3, 6))

In [40]:
dict(zip(np.array([1,2,3]), np.array([4,5,6])))

{1: 4, 2: 5, 3: 6}

In [46]:
list(zip([1,2,3],[4,5,6],[7,8,9]))

[(1, 4, 7), (2, 5, 8), (3, 6, 9)]

#### np.where return a tuple: this reflect numpy convention

In [44]:
np.where(a == 0)

(array([ 0,  2,  4,  8,  9, 10, 11]),)

In [47]:
a = np.array([[1, 2, 3, 4, 5, 6],
              [-2, 1, 2, 3, 4, 5]])

print(np.where(a > 2))

(array([0, 0, 0, 0, 1, 1, 1]), array([2, 3, 4, 5, 3, 4, 5]))


In [52]:
np.array(list(zip(np.where(a > 2)[0], np.where(a > 2)[1])))

array([[0, 2],
       [0, 3],
       [0, 4],
       [0, 5],
       [1, 3],
       [1, 4],
       [1, 5]])

#### Perform log on numpy array using mask

In [58]:
m = np.array([[1,0], [2,3]])
x = np.ma.log(m)
x

masked_array(
  data=[[0.0, --],
        [0.6931471805599453, 1.0986122886681098]],
  mask=[[False,  True],
        [False, False]],
  fill_value=1e+20)

In [59]:
x.filled(-np.inf)

array([[0.        ,       -inf],
       [0.69314718, 1.09861229]])

## 775. Inversion Problem

#### The answer below is written after referring to answers

In [152]:
from typing import Dict, List, Tuple

def global_local_inversion(A: List[int]) -> bool:
    if len(A) <= 2:
            return True
    else:
        cmax = -1
        for i in range(len(A)-2):
            cmax = max(cmax, A[i])
            if cmax > A[i+2]:
                return False
        return True

## 756. Pyramid Problem Self-written Recursive Solution

In [159]:
from collections import defaultdict

def pyramid(bottom: str, allowed: List[str]) -> bool:
    rfr = defaultdict(lambda: defaultdict(set))
    for a,b,c in allowed: rfr[a][b].add(c)
    def pyramid_set(bottom, rfr):
        if len(bottom) == 2:
            return set(rfr[bottom[0]][bottom[1]])
        else:
            return set([element 
                        for subset in 
                        [rfr[a][b] for a in pyramid_set(bottom[:-1], rfr) for b in pyramid_set(bottom[1:], rfr)] 
                        for element in subset])
    return bool(pyramid_set(bottom, rfr))          

In [155]:
pyramid(bottom = "AAB", allowed = ["AAA", "AAB", "ABA", "ABB", "BAC"])

True

In [156]:
pyramid(bottom = "AABA", allowed = ["AAA", "AAB", "ABA", "ABB", "BAC"])

False

#### Pyramid Other Answers

In [157]:
def pyramidTransition(bottom, allowed):
    f = defaultdict(lambda: defaultdict(list))
    for a, b, c in allowed: f[a][b].append(c)

    def pyramid(bottom):
        if len(bottom) == 1: return True
        for i in itertools.product(*(f[a][b] for a, b in zip(bottom, bottom[1:]))):
            if pyramid(i): return True
        return False
    return pyramid(bottom)

In [74]:
def pyramid(bottom):
    return len(bottom) == 1 or any(pyramid(i) for i in product(*(f[a][b] for a, b in zip(bottom, bottom[1:]))))

In [149]:
def pyramidTransition(bottom: str, allowed: List[str]) -> bool:
    current = [set(c) for c in bottom]
    while len(current) > 1:
        current = [set(a[2] for a in allowed if a[0] in left and a[1] in right) for left, right in zip(current[:-1], current[1:])]
    return bool(len(current[0]))

#### Defaultdict and Lambda

In [105]:
x = defaultdict(int)
x['v']
x['u']
x

defaultdict(int, {'v': 0, 'u': 0})

In [96]:
y = defaultdict(lambda: defaultdict(int))
print((y['k1']['k2']))
print(dict(y['k1']))
y

0
{'k2': 0}


defaultdict(<function __main__.<lambda>()>,
            {'k1': defaultdict(int, {'k2': 0})})

In [100]:
s = [('yellow', 1), ('blue', 2), ('yellow', 3), ('blue', 4), ('red', 1)]
d = defaultdict(list)
for k, v in s:
    d[k].append(v)
d.items()

dict_items([('yellow', [1, 3]), ('blue', [2, 4]), ('red', [1])])

In [103]:
normal_dict = {color: number for color, number in s} 
print(normal_dict)
normal_dict.items()

{'yellow': 3, 'blue': 4, 'red': 1}


dict_items([('yellow', 3), ('blue', 4), ('red', 1)])

In [109]:
z = defaultdict(lambda: 45)
z['HMM']
z

defaultdict(<function __main__.<lambda>()>, {'HMM': 45})

## 121. Stock Transaction Problem

#### At the first sight the idea of forward backward comes to mind

In [178]:
import math

def maxProfit(prices: List[int]) -> int:
    Max, Min = [-math.inf]*len(prices), [math.inf]*len(prices)
    for i in range(len(prices)):
        Max[-i-1] = max(prices[-i-1], Max[-i])
        Min[i] = min(prices[i], Min[i-1])
    return max([a-b for a,b in zip(Max, Min)])

In [179]:
maxProfit([7,1,5,3,6,4])

5

In [180]:
maxProfit([7,6,4,3,1])

0

In [186]:
def maxProfitSubmission(prices: List[int]) -> int:
    if len(prices) == 0:
        return 0
    else:
        Max, Min = [0]*len(prices), [0]*len(prices)
        cmax = prices[-1]
        cmin = prices[0]
        for i in range(len(prices)):
            if (prices[-i-1] > cmax):
                cmax = prices[-i-1]
            Max[-i-1] = cmax
            if (prices[i] < cmin):
                cmin = prices[i]
            Min[i] = cmin
        return max([a-b for a,b in zip(Max, Min)])

In [187]:
maxProfitSubmission([7,1,5,3,6,4])

5

In [188]:
maxProfitSubmission([7,6,4,3,1])

0

In [189]:
def maxProfitFast(prices: List[int]) -> int:
    diff = 0
    cmin = float('inf')
    for price in prices:
        cmin = min(price, cmin)
        diff = max(price-cmin, diff)
    return diff

In [190]:
maxProfitFast([7,1,5,3,6,4])

5

In [191]:
maxProfitFast([7,6,4,3,1])

0

## 617. Merge Two Binary Trees Problem

In [192]:
class TreeNode(object):
    def __init__(self, x):
        self.val = x
        self.left = None
        self.right = None

In [209]:
def mergeTrees(t1: TreeNode, t2: TreeNode) -> TreeNode:
    if t1 == None and t2 == None:
        return None
    elif t1 == None:
        return t2
    elif t2 == None:
        return t1
    else:
        tree_node = TreeNode(t1.val + t2.val)
        tree_node.left = mergeTrees(t1.left, t2.left)
        tree_node.right = mergeTrees(t1.right, t2.right)
        return tree_node

In [198]:
t1 = TreeNode(1)
t1.left = TreeNode(3)
t1.right = TreeNode(2)
t1.left.left = TreeNode(5)

In [199]:
t2 = TreeNode(2)
t2.left = TreeNode(1)
t2.right = TreeNode(3)
t2.left.right = TreeNode(4)
t2.right.right = TreeNode(7)

In [210]:
mergeTrees(t1, t2)

#### graphviz for graph plotting

In [204]:
from graphviz import Digraph
dot = Digraph(comment='The Round Table')
dot

In [205]:
dot.node('A', 'King Arthur')
dot.node('B', 'Sir Bedevere the Wise')
dot.node('L', 'Sir Lancelot the Brave')

dot.edges(['AB', 'AL'])
dot.edge('B', 'L', constraint='false')

In [206]:
dot.source  

'// The Round Table\ndigraph {\n\tA [label="King Arthur"]\n\tB [label="Sir Bedevere the Wise"]\n\tL [label="Sir Lancelot the Brave"]\n\tA -> B\n\tA -> L\n\tB -> L [constraint=false]\n}'

In [207]:
dot.render('test-output/round-table.gv', view=True) 

'test-output/round-table.gv.pdf'

## 11. Water Container Problem

#### This code is written the day after referring to answers, this problem is like dynamic programming, avoiding some unnecessary check, using left and right pointers

In [211]:
def maxArea(height: List[int]) -> int:
    left, right, area = 0, len(height)-1, 0
    while left < right:
        if height[left] < height[right]:
            area = max(area, height[left]*(right-left))
            left += 1
        else:
            area = max(area, height[right]*(right-left))
            right -= 1
    return area

In [212]:
maxArea([1,8,6,2,5,4,8,3,7])

49

## 2. Add Two Numbers in Singly-linked List Problem

#### Self-written class method in convenience for printing out result and create instances

In [227]:
class ListNode(object):
    
    def __init__(self, x, node=None):
        self.val = x
        self.next = node
    
    def __str__(self):
        if (self == None):
            return ""
        else:
            pointer = self
            string = str(pointer.val)
            while (pointer.next != None):
                string += " -> " + str(pointer.next.val)
                pointer = pointer.next
            return string

In [238]:
def addTwoNumbers(l1: ListNode, l2 :ListNode) -> ListNode:
    if (l1 == None) & (l2 == None):
        return None
    elif l1 == None:
        Sum = ListNode(l2.val)
        pointer = Sum
        while l2.next != None:
            pointer.next = ListNode(l2.next.val)
            l2 = l2.next
            pointer = pointer.next
        return Sum
    elif l2 == None:
        return addTwoNumbers(l2, l1)
    else:
        value_sum = l1.val + l2.val
        Sum = ListNode(value_sum % 10)
        carry = value_sum // 10
        pointer = Sum
        while (l1.next != None) & (l2.next != None):
            value_sum = l1.next.val + l2.next.val + carry
            carry = value_sum // 10
            pointer.next = ListNode(value_sum % 10)
            pointer = pointer.next
            l1 = l1.next
            l2 = l2.next
        while l1.next != None:
            value_sum = l1.next.val + carry
            carry = value_sum // 10
            pointer.next = ListNode(value_sum % 10)
            pointer = pointer.next
            l1 = l1.next
        while l2.next != None:
            value_sum = l2.next.val + carry
            carry = value_sum // 10
            pointer.next = ListNode(value_sum % 10)
            pointer = pointer.next
            l2 = l2.next
        if (carry == 0):
            return Sum
        else:
            pointer.next = ListNode(carry)
            return Sum

In [239]:
l1 = ListNode(2, ListNode(4, ListNode(3)))
print(l1)

2 -> 4 -> 3


In [240]:
l2 = ListNode(5, ListNode(6, ListNode(4)))
print(l2)

5 -> 6 -> 4


In [241]:
print(addTwoNumbers(l1, l2))

7 -> 0 -> 8


#### Import edge cases!

In [242]:
l3 = ListNode(5)
l4 = ListNode(5)
print(addTwoNumbers(l3, l4))

0 -> 1


In [244]:
l5 = ListNode(1)
l6 = ListNode(9, ListNode(9))
print(addTwoNumbers(l5, l6))

0 -> 0 -> 1


## 1. Two Sum Problem (guaranteed one solution and therefore unique elements)

In [249]:
def twoSum(nums: List[int], target: int) -> List[int]:
    for i in range(len(nums)):
        for j in range(i):
            if nums[i] + nums[j] == target:
                return [j, i]          

In [250]:
twoSum([2, 7, 11, 15], 9)

[0, 1]

#### Other answers

In [251]:
def twoSumHash(nums, target):
    dic = {}
    for i, num in enumerate(nums):
        if target-num in dic:
            return [dic[target-num], i]
        dic[num] = i

In [252]:
twoSumHash([2, 7, 11, 15], 9)

[0, 1]

## 15. Three Sum Problem (multiple solution and repeating elements)

In [267]:
def threeSumTrial(nums: List[int]) -> List[List[int]]:
    dic = {}
    output = []
    for i, num in enumerate(nums):
        for j in range(i):
            if (-nums[i]-nums[j] in dic):
                if dic[-nums[i]-nums[j]] < j:
                    output.append([-nums[i]-nums[j], nums[j], nums[i]])
        dic[num] = i
    return output

In [268]:
threeSumTrial([-1, 0, 1, 2, -1, -4])

[[-1, 0, 1], [0, 1, -1], [-1, 2, -1]]

#### How to remove or prevent repeated elements?

#### Answer below is after referring to the answers and realize the importance of sorting the list first in this problem

#### Two-pointer solution, how to avoid repeated elements is essential

In [280]:
def threeSum(nums: List[int]) -> List[List[int]]:
    if (len(nums) < 3):
        return []
    else:
        res = []
        nums = sorted(nums)
        target = nums[0] - 1
        for i in range(len(nums)-2):
            if (nums[i] != target):
                target = nums[i]
                left = i+1
                right = len(nums) - 1
                while (left < right):
                    left_number = nums[left]
                    right_number = nums[right]
                    if (left_number + right_number < -target):
                        left += 1
                        while (left < right) & (nums[left] == left_number):
                            left += 1
                    elif (left_number + right_number > -target):
                        right -= 1
                        while (left < right) & (nums[right] == right_number):
                            right -= 1
                    else:
                        res.append([target, left_number, right_number])
                        left += 1
                        while (left < right) & (nums[left] == left_number):
                            left += 1
                        right -= 1
                        while (left < right) & (nums[right] == right_number):
                            right -= 1
        return res

In [278]:
threeSum([-1, 0, 1, 2, -1, -4])

[[-1, -1, 2], [-1, 0, 1]]

In [279]:
sorted([1,3,2,4,5,7,3,5,6,6])

[1, 2, 3, 3, 4, 5, 5, 6, 6, 7]

## 17. Letter Combinations of a Phone Number

#### Recursion method, maximum depth exceeded.......

In [281]:
def letterCombinations(digits: str) -> List[str]:
    dic = {'2': ['a','b','c'], '3': ['d','e','f'], '4': ['g','h','i'], '5': ['j','k','l'],
          '6': ['m','n','o'], '7': ['p','q','r','s'], '8': ['t','u','v'], '9': ['w','x','y','z']}
    def letterHelp(digits: str):
        if (len(digits) == 1):
            return dic[digits[0]]
        else:
            return [a+b for a in letterHelp(digits[:-1]) for b in dic[digits[-1]]]
    if (len(digits) == 0):
        return []
    return letterHelp(digits)

In [282]:
letterCombinations("23")

['ad', 'ae', 'af', 'bd', 'be', 'bf', 'cd', 'ce', 'cf']

In [285]:
letterCombinations("232")

['ada',
 'adb',
 'adc',
 'aea',
 'aeb',
 'aec',
 'afa',
 'afb',
 'afc',
 'bda',
 'bdb',
 'bdc',
 'bea',
 'beb',
 'bec',
 'bfa',
 'bfb',
 'bfc',
 'cda',
 'cdb',
 'cdc',
 'cea',
 'ceb',
 'cec',
 'cfa',
 'cfb',
 'cfc']

#### Loop Method

In [286]:
def letterCombinationsLoop(digits: str) -> List[str]:
    dic = {'2': ['a','b','c'], '3': ['d','e','f'], '4': ['g','h','i'], '5': ['j','k','l'],
          '6': ['m','n','o'], '7': ['p','q','r','s'], '8': ['t','u','v'], '9': ['w','x','y','z']}
    if (len(digits) == 0):
        return []
    else:  
        output = dic[digits[0]]
        for digit in digits[1:]:
            output = [a+b for a in output for b in dic[digit]]
        return output

In [287]:
letterCombinationsLoop('23')

['ad', 'ae', 'af', 'bd', 'be', 'bf', 'cd', 'ce', 'cf']

In [288]:
letterCombinationsLoop('232')

['ada',
 'adb',
 'adc',
 'aea',
 'aeb',
 'aec',
 'afa',
 'afb',
 'afc',
 'bda',
 'bdb',
 'bdc',
 'bea',
 'beb',
 'bec',
 'bfa',
 'bfb',
 'bfc',
 'cda',
 'cdb',
 'cdc',
 'cea',
 'ceb',
 'cec',
 'cfa',
 'cfb',
 'cfc']

## 19.  Remove Nth Node From End of List

#### Seems to be very hard for a singly-linked list if we do it in one pass

#### Even though the answer is accepted, in most of the cases the original list is modified while in edge cases list remains intact

In [294]:
def removeNthFromEnd(head: ListNode, n: int) -> ListNode:
    pointer = head
    while True:
        probe = pointer
        for i in range(n):
            probe = probe.next
        if (probe == None):
            head = head.next
            return head
        elif (probe.next == None):
            pointer.next = pointer.next.next
            return head
        pointer = pointer.next

In [295]:
head = ListNode(1, ListNode(2, ListNode(3, ListNode(4, ListNode(5)))))
print(head)
print(removeNthFromEnd(head, 2))
print(head)

1 -> 2 -> 3 -> 4 -> 5
1 -> 2 -> 3 -> 5
1 -> 2 -> 3 -> 5


#### Important edge case!!!

In [296]:
l7 = ListNode(1)
print(l7)
print(removeNthFromEnd(l7, 1))
print(l7)

1
None
1


In [297]:
l8 = ListNode(1, ListNode(2))
print(l8)
print(removeNthFromEnd(l8, 2))
print(l8)

1 -> 2
2
1 -> 2


#### The problem is that it is impossible to modify the original linked-list in this case, the code written below solve the issue. Second method below keeps the list intact all the time

In [336]:
def removeNthFromEndConsistent(head: ListNode, n: int) -> ListNode:
    probe = head # check for the edge cases
    for i in range(n):
        probe = probe.next
        if (probe == None):
            if (n == 1): # The special edge cases when only 1 element is in the list
                return None
            else:
                head = head.next
                output = ListNode(head.val)
                pointer_write = output
                while (head.next != None):
                    pointer_write.next = ListNode(head.next.val) # copy everything without the first node
                    pointer_write = pointer_write.next
                    head = head.next
                return output
    else:
        pointer = head
        output = ListNode(head.val)
        pointer_write = output
        while True:
            probe = pointer
            for i in range(n):
                probe = probe.next
            if (probe.next == None):
                pointer = pointer.next # this is to skip the removed node
                while (pointer.next != None):
                    pointer_write.next = ListNode(pointer.next.val)
                    pointer_write = pointer_write.next
                    pointer = pointer.next
                return output
            pointer_write.next = ListNode(pointer.next.val) # copy the intact nodes
            pointer_write = pointer_write.next
            pointer = pointer.next  

In [333]:
head = ListNode(1, ListNode(2, ListNode(3, ListNode(4, ListNode(5)))))
print(head)
print(removeNthFromEndConsistent(head, 2))
print(head)

1 -> 2 -> 3 -> 4 -> 5
1 -> 2 -> 3 -> 5
1 -> 2 -> 3 -> 4 -> 5


In [337]:
l7 = ListNode(1)
print(l7)
print(removeNthFromEndConsistent(l7, 1))
print(l7)

1
None
1


In [338]:
l8 = ListNode(1, ListNode(2))
print(l8)
print(removeNthFromEndConsistent(l8, 2))
print(l8)

1 -> 2
2
1 -> 2


In [339]:
l9 = ListNode(1, ListNode(2, ListNode(3)))
print(l9)
print(removeNthFromEndConsistent(l9, 3))
print(l9)

1 -> 2 -> 3
2 -> 3
1 -> 2 -> 3


In [341]:
head_2 = ListNode(1, ListNode(2, ListNode(3, ListNode(4, ListNode(5, ListNode(6, ListNode(7)))))))
print(head_2)
print(removeNthFromEndConsistent(head_2, 5))
print(head_2)

1 -> 2 -> 3 -> 4 -> 5 -> 6 -> 7
1 -> 2 -> 4 -> 5 -> 6 -> 7
1 -> 2 -> 3 -> 4 -> 5 -> 6 -> 7


#### Third try: Remove after checking the length of the list (traverse the list two times)

In [344]:
def removeNthFromEndLengthMethod(head: ListNode, n: int) -> ListNode:
    length = 0
    pointer = head
    while (pointer != None):
        length += 1
        pointer = pointer.next
    if (n == length):
        if (n == 1):
            return None
        else:
            head = head.next
            output = ListNode(head.val)
            pointer_write = output
            while (head.next != None):
                pointer_write.next = ListNode(head.next.val) # copy everything without the first node
                pointer_write = pointer_write.next
                head = head.next
            return output
    else:
        output = ListNode(head.val)
        pointer = head.next
        pointer_write = output
        for i in range(length-n-1):
            pointer_write.next = ListNode(pointer.val)
            pointer = pointer.next
            pointer_write = pointer_write.next
        
        pointer = pointer.next
        
        while (pointer != None):
            pointer_write.next = ListNode(pointer.val)
            pointer = pointer.next 
            pointer_write = pointer_write.next
        return output

In [345]:
print(head)
print(removeNthFromEndLengthMethod(head, 2))
print(head)

1 -> 2 -> 3 -> 4 -> 5
1 -> 2 -> 3 -> 5
1 -> 2 -> 3 -> 4 -> 5


In [350]:
print(l7)
print(removeNthFromEndLengthMethod(l7, 1))
print(l7)

1
None
1


In [351]:
print(l8)
print(removeNthFromEndLengthMethod(l8, 2))
print(l8)

1 -> 2
2
1 -> 2


In [352]:
print(l9)
print(removeNthFromEndLengthMethod(l9, 3))
print(l9)

1 -> 2 -> 3
2 -> 3
1 -> 2 -> 3


In [353]:
print(head_2)
print(removeNthFromEndLengthMethod(head_2, 5))
print(head_2)

1 -> 2 -> 3 -> 4 -> 5 -> 6 -> 7
1 -> 2 -> 4 -> 5 -> 6 -> 7
1 -> 2 -> 3 -> 4 -> 5 -> 6 -> 7


## 21. Merge Two Sorted Lists

In [362]:
def mergeTwoLists(l1: ListNode, l2: ListNode) -> ListNode:
    if (l1 == None) & (l2 == None):
        return None
    elif (l2 == None):
        output = ListNode(l1.val)
        pointer = output
        l1 = l1.next
        while (l1 != None):
            pointer.next = ListNode(l1.val)
            l1 = l1.next
            pointer = pointer.next
        return output
    elif (l1 == None):
        output = ListNode(l2.val)
        pointer = output
        l2 = l2.next
        while (l2 != None):
            pointer.next = ListNode(l2.val)
            l2 = l2.next
            pointer = pointer.next
        return output
    if (l1.val <= l2.val):
        output = ListNode(l1.val)
        l1 = l1.next
    else:
        output = ListNode(l2.val)
        l2 = l2.next
    pointer = output
    while (l1 != None) & (l2 != None):
        if (l1.val <= l2.val):
            pointer.next = ListNode(l1.val)
            l1 = l1.next
            pointer = pointer.next
        else:
            pointer.next = ListNode(l2.val)
            l2 = l2.next
            pointer = pointer.next
    if (l1 == None):
        pointer.next = mergeTwoLists(l2, None)
    else:
        pointer.next = mergeTwoLists(l1, None)
    return output

In [363]:
first_sll = ListNode(1, ListNode(2, ListNode(4)))
second_sll = ListNode(1, ListNode(3, ListNode(4)))
print(mergeTwoLists(first_sll, second_sll))

1 -> 1 -> 2 -> 3 -> 4 -> 4
